CREATE TABLE IF NOT EXISTS ACCOUNT (
    ACCOUNTID serial PRIMARY KEY,
    USERNAME VARCHAR(20),
    EMAIL VARCHAR(20),
    PASSWORD VARCHAR(255) NOT NULL
);

TRUNCATE TABLE ACCOUNT;

CREATE TABLE IF NOT EXISTS PROJECT (
    ID serial PRIMARY KEY,
    NAME VARCHAR(20),
    TYPE VARCHAR(10),
    STARTDATE DATE,
    VERSIONNO BIGINT
);
